---
title: <span style="color:#034a94"> **R - Validación de supuestos**</span>
author: "Modelos Estadísticos para la toma de decisiones"
output:
  html_document:
    code_folding: hide
    css: style.css
---



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(paqueteMODELOS)
data("arboles1")
arboles1$D1 = as.numeric(arboles1$mg=="GENOTIPO_2")
arboles1$D2 = as.numeric(arboles1$finca=="FINCA_2")
arboles1$D3 = as.numeric(arboles1$finca=="FINCA_3")
arboles1$peso = as.numeric(arboles1$peso)
arboles1$diametro = as.numeric(arboles1$diametro)
arboles1$altura = as.numeric(arboles1$altura)


library(tidyverse)
library(lmtest) # diagnosticos de modelos lineales
library(sandwich) # errores estandar robustos
library(ggeffects) # efectos y predicciones en modelos de regresion
library(modelsummary) # tablas de regresion
```


</br></br>

```{r}
modelo1 <- lm(peso ~ diametro + altura + D2 + D3, data = arboles1)
summary(modelo1)
```

</br>

El modelo presenta un $R^{2} = 0.8538$, indicando un ajuste del 85% de los datos al modelo. Si deseamos compararlo con otro modelo con igual variable dependiente, utilizamos el $R^{2}_{adj} = 0.847$ 


</br></br>

### **Validación de supuestos gráficamente**

``{r}
par(mfrow = c(2, 2))
plot(modelo1)
```






