---
title: <span style="color:#034a94">**R - Análisis descriptivo**</span>
author: "Modelos Estadísticos para la toma de decisiones"
output:
  html_document:
    code_folding: hide
    css: style.css
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA)

library(paqueteMODELOS)
data("arboles1")
arboles1$D1 = as.numeric(arboles1$mg=="GENOTIPO_2")
arboles1$D2 = as.numeric(arboles1$finca=="FINCA_2")
arboles1$D3 = as.numeric(arboles1$finca=="FINCA_3")
arboles1$peso = as.numeric(arboles1$peso)
arboles1$diametro = as.numeric(arboles1$diametro)
arboles1$altura = as.numeric(arboles1$altura)


library(tidyverse)
library(lmtest) # diagnósticos de modelos lineales
library(sandwich) # errores estándar robustos
library(ggeffects) # efectos y predicciones en modelos de regresión
library(modelsummary) # tablas de regresión

#install.packages("bbmle")
#install.packages("stats4")


```


</br></br>

## <span style="color:#034a94">**Exploración previa**</span>

En esta etapa se realiza una exploración de la data, tipo de variables, datos faltantes, datos atípicos. Podemos realizarlo con la función `summary()` o con 
</br>

```{r, warning=FALSE, message=FALSE}
library(paqueteMODELOS)
library(tidyverse)
library(modelsummary)
data("arboles1")
arboles1$D1 = as.numeric(arboles1$mg=="GENOTIPO_2")
arboles1$D2 = as.numeric(arboles1$finca=="FINCA_2")
arboles1$D3 = as.numeric(arboles1$finca=="FINCA_3")
arboles1$peso = as.numeric(arboles1$peso)
arboles1$diametro = as.numeric(arboles1$diametro)
arboles1$altura = as.numeric(arboles1$altura)

summary(arboles1)
# modelsummary::datasummary_skim(arboles1)
# library(stats4) # para la función mle
# library(bbmle) # para la función mle2
```
</br></br>


```{r}
glimpse(arboles1)
```

</br></br></br>

## <span style="color:#034a94">**Asociación entre las variables cuantitativas**</span>


```{r, warning=FALSE, message=FALSE, fig.align='center'}
library(GGally)
ggpairs(arboles1[,3:5], title=" ") 
```
