<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />


<meta name="author" content="Modelos Estadísticos para la toma de decisiones" />


<title>Variables categóricas en el modelo de regresión lineal</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/bootstrap.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<script src="site_libs/navigation-1.1/codefolding.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>






<link rel="stylesheet" href="style.css" type="text/css" />



<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->
<style type="text/css">
.code-folding-btn { margin-bottom: 4px; }
</style>




</head>

<body>


<div class="container-fluid main-container">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Modelos Estadísticos para la toma de decisiones</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Conceptos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso005.html">Modelo de Regresión Lineal Múltiple</a>
    </li>
    <li>
      <a href="recurso010.html">Correlación</a>
    </li>
    <li>
      <a href="recurso015.html">Algebra Lineal</a>
    </li>
    <li>
      <a href="recurso020.html">Notación matricial de modelo</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Estimación
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso030.html">Mínimos Cuadrados Ordinarios</a>
    </li>
    <li>
      <a href="recurso035.html">Propiedades de los estimadores</a>
    </li>
    <li>
      <a href="recurso050.html">Validación de los supuestos</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Inferencia
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso040.html">Inferencia sobre los parámetros</a>
    </li>
    <li>
      <a href="recurso042.html">Inferencia sobre subconjunto de parámetros</a>
    </li>
    <li>
      <a href="recurso045.html">Pronósticos</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Ajuste del modelo
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso055.html">Indicadores de ajuste</a>
    </li>
    <li>
      <a href="recurso060.html">Validación cruzada</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Variables cat.
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso061.html">En el modelo de RLM</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Multicolinealidad
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso080.html">Multicolinealidad</a>
    </li>
    <li>
      <a href="recurso081.html">Causas / Efectos</a>
    </li>
    <li>
      <a href="recurso082.html">Diagnóstico</a>
    </li>
    <li>
      <a href="recurso083.html">Alternativas</a>
    </li>
  </ul>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Código R 
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="recurso099.html">Análisis previo</a>
    </li>
    <li>
      <a href="recurso100.html">Estimación MCO</a>
    </li>
    <li>
      <a href="recurso120.html">Validación cruzada</a>
    </li>
    <li>
      <a href="recurso140.html">Mapa</a>
    </li>
  </ul>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">

<div class="btn-group pull-right float-right">
<button type="button" class="btn btn-default btn-xs btn-secondary btn-sm dropdown-toggle" data-toggle="dropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><span>Code</span> <span class="caret"></span></button>
<ul class="dropdown-menu dropdown-menu-right" style="min-width: 50px;">
<li><a id="rmd-show-all-code" href="#">Show All Code</a></li>
<li><a id="rmd-hide-all-code" href="#">Hide All Code</a></li>
</ul>
</div>



<h1 class="title toc-ignore"><span
style="color:#034a94"><strong>Variables categóricas en el modelo de
regresión lineal</strong></span></h1>
<h4 class="author">Modelos Estadísticos para la toma de decisiones</h4>

</div>


<p></br></br></p>
<p>Cuando se desea incluir variables categóricas al modelo de regresión
lineal múltiple es necesario crear variables conocidas como ficticias,
llamadas tambien binarias o dicotómicas. Estas variables se redefinen a
aprtir de las categorías de la variable cualitativa a ser incluida en el
modelo y solo puede tomar dos valores : 0 ó 1.</p>
<p>En el caso de una variable categórica con <span
class="math inline">\(k\)</span> categorías, es necesaria la
construcción de <span class="math inline">\((k-1\)</span> variables
binarias</p>
<p></br></br></br></p>
<div id="ejemplo" class="section level3">
<h3><span style="color:#FF7F00"> <strong>Ejemplo</strong></span></h3>
<p></br></p>
<p>La base de datos arboles1 contiene las siguientes variables:</p>
<p></br></p>
<table>
<colgroup>
<col width="25%" />
<col width="75%" />
</colgroup>
<tbody>
<tr class="odd">
<td align="left"><strong>finca</strong></td>
<td align="left">finca donde se ubica el árbol : FINCA_1, FINCA_2 y
FINA_3</td>
</tr>
<tr class="even">
<td align="left"><strong>mg</strong></td>
<td align="left">genotipo del árbol : GENOTIPO_1, GENOTIPO_2</td>
</tr>
<tr class="odd">
<td align="left"><strong>peso</strong></td>
<td align="left">peso del árbol</td>
</tr>
<tr class="even">
<td align="left"><strong>diametro</strong></td>
<td align="left">diametro del árbol</td>
</tr>
<tr class="odd">
<td align="left"><strong>altura</strong></td>
<td align="left">altura del árbol</td>
</tr>
</tbody>
</table>
<p></br></p>
<p>Para incluir las variables mg con dos categorías utilizamos una
variable binaria <span class="math inline">\(D_1\)</span> que puede
tomar el nombre de uno de sus valores así:</p>
<p></br></p>
<p><span class="math display">\[D_{1i} = \left \{ \begin{matrix}
                       1 &amp;  \text{ mg= GENOTIPO_2} \\
                         &amp;  \\
                       0 &amp; \text{mg =
GENOTIPO_1}\end{matrix}\right.  \]</span></p>
<p></br></p>
<p>En este caso el rango de la varuiable es: <span
class="math inline">\(R_D =\{0,1\}\)</span>, temiendo como referencia o
base al GENOTIPO_1</p>
<p></br></p>
<pre class="r"><code>library(paqueteMODELOS)
data(&quot;arboles1&quot;)
arboles1$D1=as.numeric(arboles1$mg==&quot;GENOTIPO_2&quot;)</code></pre>
<p></br></p>
<p>El modelo de regresión que solo incluye la variable
<strong>mp</strong> como predictora es:</p>
<p></br></p>
<p><span class="math display">\[\text{peso}_{i} =  \beta_{0} + \beta_{1}
D_{1i} + \varepsilon_{i} \]</span></p>
<p></br></p>
<p>Y el modelo estimado</p>
<p></br></p>
<p><span class="math display">\[\widehat{\text{peso}}_{i}
=  \widehat{\beta}_{0} + \widehat{\beta}_{1} D_{1i} \]</span></p>
<p></br></p>
<p>Cuando el individuo observado pertenece al genotipo 1, la variable
<span class="math inline">\(D_{i}\)</span> toma el valor de cero
luego:</p>
<p></br></p>
<p><span class="math display">\[\widehat{\text{peso}}_{i}
=  \widehat{\beta}_{0} + \widehat{\beta}_{1} (0)  = \widehat{\beta}_{0}
\]</span></p>
<p></br></p>
<p>En caso de pertenecer al genotipo, la la variable D_{i} toma el valor
de uno y el valor de la estimación del peso sería:</p>
<p></br></p>
<p><span class="math display">\[\widehat{\text{peso}}_{i}
=  \widehat{\beta}_{1} + \widehat{\beta}_{1} (1)  = \widehat{\beta}_{0}
+ \widehat{\beta}_{1} \]</span></p>
<p></br></p>
<p>Indicando que <span
class="math inline">\(\widehat{\beta}_{1}\)</span> corresponde al valor
del peso estimado adicional (si el signo del coeficiente es positivo)
por ser el árbol del genotipo 2, con respecto al gonotipo 1.</p>
<p></br></p>
<p>Para la variable finca con tres categorias, es necesario la creación
de dos variables binarias, las cuales pueden ser generadas por R y en
caso de tener una intensión especial la construcción de las variables
será necesario realizarlas previamente a la estimación del modelo.</p>
<p></br></br></p>
</div>
<div id="nota" class="section level3 content-box-gray">
<h3><span style="color:#686868"> <strong>Nota</strong></span></h3>
<p></br> La estimación en R genera las variables binarias para las
categorías FINCA_2 y FINCA_3, dejando como base la categoría FINCA_1,
esto es equivalente a construir dos variables adicionales a la base:</p>
</div>
<p></br></br></p>
<pre>
# A tibble: 90 × 7
   finca   mg         peso  diametro altura    D2    D3
   <chr>   <chr>      <chr> <chr>    <chr>  <dbl> <dbl>
 1 FINCA_1 GENOTIPO_1 13.73 4.7      5          0     0
 2 FINCA_1 GENOTIPO_1 14.58 5.3      5.6        0     0
 3 FINCA_1 GENOTIPO_1 15.88 4.8      5.8        0     0
 4 FINCA_1 GENOTIPO_1 8.99  3.2      4.3        0     0
 5 FINCA_1 GENOTIPO_1 6.99  2.2      3.3        0     0
.
31 FINCA_2 GENOTIPO_2 16.24 5.8      8.1        1     0
32 FINCA_2 GENOTIPO_2 16.08 5.9      7.5        1     0
33 FINCA_2 GENOTIPO_2 23.82 7.1      9.3        1     0
34 FINCA_2 GENOTIPO_2 30.83 7.9      10.9       1     0
35 FINCA_2 GENOTIPO_2 26.38 7.1      9.2        1     0
.
61 FINCA_3 GENOTIPO_2 13.98 4.7      5.8        0     1
62 FINCA_3 GENOTIPO_2 24.47 6        7.2        0     1
63 FINCA_3 GENOTIPO_2 22.82 6.7      7.8        0     1
64 FINCA_3 GENOTIPO_2 21.8  6.8      7.3        0     1
65 FINCA_3 GENOTIPO_2 18.12 5.9      7.7        0     1
.
</pre>
<p></br></p>
<p></br></p>
<p>El modelo de regresión que incluye esta variable es:</p>
<p></br></p>
<p><span class="math display">\[\text{peso}_{i} =  \beta_{0} + \beta_{1}
D_{2i} + \beta_{3} D_{3i} + \varepsilon_{i}\]</span></p>
<p></br></br></p>
<p>Y su estumación MCO :</p>
<pre class="r"><code>library(paqueteMODELOS)
data(&quot;arboles1&quot;)
arboles1$D2=as.numeric(arboles1$finca==&quot;FINCA_2&quot;)
arboles1$D3=as.numeric(arboles1$finca==&quot;FINCA_3&quot;)

modelo1 &lt;- lm(peso ~ D2+D3, data = arboles1)
summary(modelo1)</code></pre>
<pre><code>## 
## Call:
## lm(formula = peso ~ D2 + D3, data = arboles1)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -17.042  -5.264  -1.363   3.308  24.848 
## 
## Coefficients:
##             Estimate Std. Error t value Pr(&gt;|t|)    
## (Intercept)   13.086      1.291  10.136  &lt; 2e-16 ***
## D2             9.936      1.826   5.442 4.79e-07 ***
## D3             7.104      1.826   3.891 0.000195 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## Residual standard error: 7.071 on 87 degrees of freedom
## Multiple R-squared:  0.2655, Adjusted R-squared:  0.2486 
## F-statistic: 15.72 on 2 and 87 DF,  p-value: 1.484e-06</code></pre>
<p></br></br></p>
<p><span class="math inline">\(D_{2} = 9.936\)</span> se interpreta con
el precio promedio adicional que tiene el árbol ubicado en la FINCA2, en
comparación con el promedio del peso de los árboles ubicados en la
FINCA1.</p>
<p></br></p>
<p><span class="math inline">\(D_{3} = 7.104\)</span> se interpreta con
el precio promedio adicional que tiene el árbol ubicado en la FINCA3, en
comparación con el promedio del peso de los árboles ubicados en la
FINCA1.</p>
<p></br></p>
<p>Si el árbol pertenece a la FINCA1, el valor de (<span
class="math inline">\(D_1\)</span>, <span
class="math inline">\(D_2\)</span>), será (0,0) y en el modelo presendo
corresponderá a un peso promedio de <span
class="math inline">\(13.086\)</span></p>
<p></br></br></p>
<div id="nota-1" class="section level3 content-box-gray">
<h3><span style="color:#686868"> <strong>Nota</strong></span></h3>
<p>La variable finca que corresponde a tres categorías se representa con
dos variables binarias</p>
<table>
<thead>
<tr class="header">
<th align="left">finca</th>
<th align="center"><span class="math inline">\(D_2\)</span></th>
<th align="center"><span class="math inline">\(D_3\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">FINCA1</td>
<td align="center">0</td>
<td align="center">0</td>
</tr>
<tr class="even">
<td align="left">FINCA2</td>
<td align="center">1</td>
<td align="center">0</td>
</tr>
<tr class="odd">
<td align="left">FINCA3</td>
<td align="center">0</td>
<td align="center">1</td>
</tr>
</tbody>
</table>
</div>




</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->
<script>
$(document).ready(function () {
  window.initializeCodeFolding("hide" === "show");
});
</script>


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
